# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('avatar_url', models.URLField(null=True)),
                ('repos_url', models.URLField(null=True)),
                ('type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, null=True)),
                ('company', models.CharField(max_length=30, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
