# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='login',
            field=models.CharField(max_length=30),
        ),
    ]
